### PR TITLE
added a generic SetMatcherEditor

### PR DESCRIPTION
**Pull request by fab1an**

### CODE REVIEW

**Comment by fab1an** [comment]
I use this a lot, though in my code I usually use `ImmutableSet` from guava. I changed it to regular `Set` for this PR, but I'm not copying them. Maybe that should be done…

**Comment by hbrands** [comment]
I think SetMatcherEditor#setMode should do only something, if the new mode is different from the old mode. Also, it should check if there is already a MatchSet specified, before doing fireMatchAll / fireMatchNone.

Currently, the MatchSet of SetMatcherEditor acts like a whitelist: it matches elements that are contained in the MatchSet. Something like a blacklist is also useful: Match elements that are **not** contained in the MatchSet.

**Comment by fab1an** [comment]
I'm fine with all your suggestions. Do you have an idea whether the input set should be copied or not?

**Comment by hbrands** [comment]
As SetMatcher should be immutable, yes I would copy the input set.
Maybe SetMatcherEditor can be changed to not store the MatchSet itself to avoid double copying.
It could get the current MatchSet from the current matcher (#getMatcher()).

**Comment by fab1an** [comment]
But it would have to cast the Matcher that way, wouldn't it?

A related question: If I do "fireMatchAll()", do I have to update or clear the `Matcher` as well?

**Comment by hbrands** [comment]
Yes, that's the downside. 
Also, fireMatchAll / fireMatchNone will change the current Matcher to TrueMatcher / FalseMatcher.

**Comment by hbrands** [comment]
I'd change the Mode of SetMatcherEditor to Mode.BLACKLIST / Mode.WHITELIST.
Mode.WHITELIST will match elements contained in the match set. If the match set is empty, no element is matched.
Mode.BLACKLIST will match elements **not** contained in the match set. If the match set is empty, all elements are matched.

**Comment by fab1an** [comment]
I updated it for a BLACKLIST/WHITELIST, but I kept the second flag for the empty-match behaviour.

The reason is that I'm supporting an application similar to ITunes with multiple filters in a sidebar. Not selecting any filter should display the entire list.

**Comment by hbrands** [comment]
Ok, I see.
Will you update this pull request with your changes to include it in version 1.10?
Or do you prefer to include this functionality after we moved to gradle (1.11)?

**Comment by fab1an** [comment]
I will update it.

**Comment by fab1an** [comment]
Updated everything. It now has BLACKLIST/WHITELIST like you described, because that's more logical. I also removed the mode-setting function alltogether for now.

**Comment by fab1an** [comment]
I realized that for my use case to work I need to either add the method `setMode`, to change the mode from whitelist to blacklist when the set is empty **OR** I add a third mode `WHITELIST_EMPTY_MATCHES_ALL`. I can't think of any use for the diametral `BLACKLIST_EMPTY_MATCHES_NONE`, but I use the first behaviour literally everywhere I use SetMatcherEditor.

What do you think?

**Comment by hbrands** [comment]
Would it suffice to fireMatchAll in the constructor of SetMatcherEditor?
When a dedicated MatchSet is given via the setter method the logic I described earlier above would be applied. E.g. when the SetMatcherEditor is constructed the MatchSet is assumed to be undefined/not set.

**Comment by fab1an** [comment]
Not sure I understand. At the moment it works like you described earlier. Mode blacklist + empty set matches all items, mode whitelist + empty set matches none.

**Comment by hbrands** [comment]
Currently you fireMatchNone in the constructor if the Mode is WHITELIST, because you assume that the MatchSet is empty. But if we'd assume in the constructor that the MatchSet is yet undefined/not set, we wouldn't filter anything, e.g. we'd apply fireMatchAll in the constructor. Only if the MatchSet is updated via the setter method we'd assume a defined MatchSet and apply the filter logic.

**Comment by fab1an** [comment]
What is the benefit of that?

**Comment by hbrands** [comment]
We don't need a third Mode value `WHITELIST_EMPTY_MATCHES_ALL` then.
But perhaps **I** misunderstood **your** use case...

**Comment by fab1an** [comment]
Okay, my users just want this:

1. Application starts, no filter is selected -> the entire list is shown: (mode whitelist would show an empty list)

screen shot 2017-01-23 at 17 54 51

2. User selects one filter: the list is filtered according to normal whitelist rules, only "Open" issues are shown:

screen shot 2017-01-23 at 17 55 01

3. User deselects the filter -> all issues are shown again

**Comment by hbrands** [comment]
Ok, I now understand better. My proposal only works for 1. and 2., but not for 3.
I think two WHITELIST modes are appropriate here:
WHITELIST_EMPTY_MATCHES_ALL
WHITELIST_EMPTY_MATCHES_NONE

I agree that we only need one mode for BLACKLIST.

**Comment by fab1an** [comment]
I updated it according to your suggestions. The set is now kept in the Matcher.

**Comment by hbrands** [comment]
I merged your pull request into master.
I fixed one issue with respect to BLACKLIST filtering. SetMatcher has to respect the mode.
I extended the test case, reformatted some code and added some Javadoc.
I will publish a new snapshot version with the changes in a moment.
Thanks for your contribution!

**Comment by fab1an** [comment]
Thanks for adding the documentation and merging this!

**Pull request merged**
