### PR TITLE
Gradle build

### PR DESCRIPTION
**Pull request by fab1an**
1. commit consists only of renames into gradle-layout and splitting up tests.
2. commit adds gradle-wrapper, so one can build everything without needing a local gradle-installation 
3. commit adds build-configuration

**Commands are the same as the ant-build:**
````bash
./gradlew clean
./gradlew test                          # test everything
./gradlew jar                           # build the osgi jar with everything
./gradlew build -x test                 # build everything without testing
./gradlew compileJava                   # compile everything
./gradlew :core:jar                     # jar with core only (core/build/libs/core.jar)
./gradlew :extensions:swt:compileJava   # compile swt extension only (and required core)
./gradlew :extensions:swt:test          # test swt only 
````

It should be possible to use syntactic Java 7 features like `<>` in the code now.

### CODE REVIEW

**Comment by fab1an** [comment]
I saw that the original build added the javaFx `rt.jar`, so that the build would work on jdk7, but is that a good idea?

**Comment by hbrands** [comment]
I think it was added to work with Java 6. It's version 2.2.21.
As of Java 7 Update 6, JavaFx is part of the Oracle Java SE implementation.
But the jfxrt.jar is not automatically added to the classpath. It has to be done manually.
It's located in the lib directory of the JRE. On Java 7 we should take this one.
(With Java 8 JavaFx is automatically added to the classpath.)

**Comment by fab1an** [comment]
I fixed the jdk7 build.

**Comment by fab1an** [comment]
Holger, I think I can complete this transition this week. Do you want to include it into `1.10` as well?

**Comment by fab1an** [comment]
Nevermind, I found a couple more difficulties. Could you tell me if there are parts of the old buildsystem which aren't needed anymore. In particular:

* the m4 macros
* the jars for javadocs, sources, and dist (all of these are available on github, no?)

Also I could package the issuesbrowser and the xmlbrowser in such a way that it is runnable from a single jar.

**Comment by hbrands** [comment]
We'll release and deploy version 1.10 with the ant build as planned.
I think we need all capabilities of the old build, OSGI manifests, building of javadocs, sources and dist and the m4 stuff. That's for example used to generate FourColorTree and SimpleTree from BciiTree when there is a need to change something.
For creating the OSGI manifest the bnd tool is used. I think there is a [gradle plugin](https://github.com/bndtools/bnd/blob/master/biz.aQute.bnd.gradle/README.md#create-a-task-of-the-bundle-type) for this.

**Comment by fab1an** [comment]
Okay. The osgi-stuff should work already.

**Comment by fab1an** [comment]
This should be complete, all the old tasks work. 

* There are a couple of differences in the generated OSIG-manifest has some changes because I took the latest version of the bndtools. 
* javadoc is in the new format, links to SWT etc. are fixed.

**Comment by hbrands** [comment]
Hi Fabian,
I just started testing your Gradle build.
When running on Java 7 the "docs" task seems to have a problem. It does not know the -Xdoclint:none flag. I think it's only available on Java 8. Also the link to javase/6 could be updated to javase/7

**Comment by hbrands** [comment]
Have you tried to separate the swing and io extensions out of the core?
That's from the old ANT build:
swing:
			<include name="**/swing/**"/>
			<exclude name="**/migrationkit/**"/>

io:
			<include name="**/ctp/**"/>
			<include name="**/io/**"/>
			<include name="**/nio/**"/>
			<include name="**/pmap/**"/>
			<include name="**/rbp/**"/>

**Comment by hbrands** [comment]
I'm in favour to drop the migrationkit classes and related tests:

migrationkit:
            include name="**/migrationkit/**"

**Comment by hbrands** [comment]
Never mind, we can fix remaining issues on master after merge.
Thanks for the pull request!

**Comment by fab1an** [comment]
Thanks for merging, Holger. Sorry for the late reply, when I have a little more time, I'll look into the remaining issues.

**Comment by hbrands** [comment]
Hi Fabian,
do you know a solution to this problem generating JavaDocs with excludes:
https://discuss.gradle.org/t/javadoc-exclusion-question/11875/4
It seems we have the same problem for the impl packages that should be excluded.

**Pull request merged**
