### PR TITLE
Proper getOldValue/getNewValue implementation without breaking API

### PR DESCRIPTION
**Pull request by swimmesberger**
I have properly implemented getOldValue/getNewValue preserving the public API. The GC pressure could potentially be much higher as before (because of more object creation) but the overall event performance should be better. 
I have also fixed the BlockSequence implementation (like in the old 1.5 (?) glazedlists days) so that it covers more cases.

### CODE REVIEW

**Comment by robeden** [comment]
Could you provide a little background on the problems you're solving? What is your approach? Any advantages or disadvantages (other than the previously mentioned GC pressure)?

I can read the code and draw my own conclusions, but it's good to make sure we're on the same page.

**Comment by hbrands** [comment]
@swimmesberger I appreciate your efforts, but why do you mix different aspects into one pull request now?
For example, changes to the travis build or debugging enhancements don't fit the original goal of this pull request.
It makes reviewing and accepting the PR more complicated.

**Comment by swimmesberger** [comment]
Sorry I will create a sepa branch for this changes only but I started to work on a fork of the library so it fits our needs. I thought that there is not much development going on at this repository but I will try to separate and upstream as much as possible.

**Comment by hbrands** [comment]
@swimmesberger That would be helpful. 
It's true that the development has slowed down. Rob and I are supporting this library in our free time. So there are times when we are more or less active.
Reworking the getOldValue/getNewValue implementation is an important topic we'll address in the next major release (2.0). Before that we want to get 1.12 out with a Java 8 baseline.

**Comment by swimmesberger** [comment]
Lets continue here:
#673

**Pull request closed without merging**
