### PR TITLE
new build module: jmh-benchmark

### PR DESCRIPTION
**Pull request by fab1an**
I've added a module with a Sample-JMH benchmark and a shellscript that compiles and starts the benchmarks automatically.

This follows the recommendation of creating a separate benchmark jar and start it in a fresh JVM.

### CODE REVIEW

**Comment by hbrands** [comment]
Thanks for the setup.

**Comment by fab1an** [comment]
Gladly. Thanks for merging!

**Comment by fab1an** [comment]
Oh, i just realized this needs to be excluded from the jar.

**Comment by robeden** [comment]
This will be nice to have, thanks @fab1an!

**Pull request merged**
